name: Scrape Rank Data
on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10am UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r _scripts/requirements.txt

      - name: Run Rank Scraper
        run: python _scripts/ScrapeRanks.py _data/ranks.json
      - name: Commit Rank Data
        run: |
          git config --global user.name 'wavdl'
          git config --global user.email 'billy@wavdl.blog'
          git add _data/ranks.json
          git commit -m "Automated Rank Data Update"
          git push